export const DEFEAT_QUOTES: string[] = [
  'Oh no! YURIV believes in your comeback! 🚀',
  'You got this! Just dodge a little better next time! 💪',
  'That was a close one! Stars are still out there waiting! ⭐',
  'Enemies got lucky this time. Show them who’s boss next round! 😜',
  'Defeat? Just a minor setback. YURIV is ready for the next try! 🏆',
  'Don’t worry, those stars will be yours soon enough! 🌟',
  'You call that a defeat? I call that practice! 😉',
  'That’s tough. Ready to dive back in? 🌌',
  'Shake it off! The next challenge is yours for the taking! 🎮',
  'Enemies may have won this round, but the war isn’t over! 👾',
  'Have you tried, like, not dying? 💀',
  'Dunno, maybe swap your augments every once in a while?',
  'Pro tip: Avoid getting hit. 🤔',
  'Oops! Did you forget to dodge?',
  'Maybe those enemies are just too good… or not. 🤷‍♂️',
  'Ever considered dodging? Just a thought. 😉',
  'Yikes! That was brutal. Time to rethink your strategy!',
  'Defeated again? Maybe third time’s the charm?',
];
