
services:
  dodge_backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env

  dodge_frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:80"
    env_file:
      - ./frontend/.env.local
    depends_on:
      - dodge_backend