
services:
  dodge_mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: adminTest
      MONGO_INITDB_ROOT_PASSWORD: passwordTest

  dodge_backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - dodge_mongo

  dodge_frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:80"
    env_file:
      - ./frontend/.env.local
    depends_on:
      - dodge_backend

volumes:
  mongo-data: