
services:
  dodge_backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
      - CYPHER_KEY=${CYPHER_KEY}
      - JWT_KEY=${JWT_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - MANAGER_EMAIL=${MANAGER_EMAIL}
      - SERVER_EMAIL=${SERVER_EMAIL}
      - SERVER_EMAIL_PASS=${SERVER_EMAIL_PASS}
      - FRONTEND_URL=${FRONTEND_URL}

  dodge_frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - VITE_CLIENT_ID=${VITE_CLIENT_ID}
      - VITE_CLIENT_SECRET=${VITE_CLIENT_SECRET}
      - VITE_CYPHER_KEY=${VITE_CYPHER_KEY}
    depends_on:
      - dodge_backend
