openapi: 3.0.0
info:
  title: Your API Title
  version: 1.0.0
  description: Your API description
servers:
  - url: http://localhost:3005
paths:
  /api/user/login:
    post:
      tags:
        - User Controller
      summary: Login as a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                  default: johndoe
                password:
                  type: string
                  default: johnDoe20!@
      responses:
        '201':
          description: Created
        '404':
          description: Not Found
        '409':
          description: Conflict
        '500':
          description: Server Error
  /users:
    get:
      summary: Retrieve a list of users
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
components:
  schemas:
    User:
      type: object
      required:
        - id
        - name
        - email
      properties:
        id:
          type: string
          description: The user ID
        name:
          type: string
          description: The username
        email:
          type: string
          description: The user email
      example:
        id: d5fE_asz
        name: John Doe
        email: john.doe@example.com
tags: []
