export enum VFX {
  PULSE_RED = 'PULSE_RED',
  PULSE_LIGHT_BLUE = 'PULSE_LIGHT_BLUE',
  PULSE_PURPLE = 'PULSE_PURPLE',
  PULSE_GREEN = 'PULSE_GREEN',
  PULSE_HACKED = 'PULSE_HACKED',
  PULSE_GOLD = 'PULSE_GOLD',
  PULSE_IMMUNITY = 'PULSE_IMMUNITY',
  PULSE_PORTAL = 'PULSE_PORTAL',
  PULSE_DEATHMARK = 'PULSE_DEATHMARK',
}
